---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    tier: mysql
spec:
  type: ClusterIP
  selector:
    app: wordPress
    tier: mysql
  ports:
    - port: 3306
      targetPort: 3306
---