---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    tier: wordpress-frontend
spec:
  type: LoadBalancer
  selector:
    app: wordPress
    tier: wordpress-frontend
  ports:
    - port: 80
      nodePort: 31000
---