---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordPress
    tier: wordpress-frontend
spec:
  selector:
    matchLabels:
      app: wordPress
      tier: wordpress-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: wordPress
        tier: wordpress-frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress:php7.1-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-svc
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
---