---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    tier: wordpress-frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: wordpress-sc
  resources:
    requests:
      storage: 5Gi
---