---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc
  labels:
    tier: wordpress-frontend
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0f8984a3b82232d04
  directoryPerms: "777"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/wordpress"
  accessPoints: fsap-093932a0cf72c4c95
---
